Class {
	#name : 'UserBook',
	#superclass : 'Object',
	#instVars : [
		'id',
		'username',
		'title',
		'author',
		'genre',
		'year',
		'rating',
		'impression',
		'dateAdded'
	],
	#category : 'SpecComponentsLibrary-Examples',
	#package : 'SpecComponentsLibrary',
	#tag : 'Examples'
}

{ #category : 'accessing' }
UserBook >> author [

	^ author
]

{ #category : 'accessing' }
UserBook >> author: anObject [

	author := anObject
]

{ #category : 'accessing' }
UserBook >> dateAdded [

	^ dateAdded
]

{ #category : 'accessing' }
UserBook >> dateAdded: anObject [

	dateAdded := anObject
]

{ #category : 'accessing' }
UserBook >> genre [

	^ genre
]

{ #category : 'accessing' }
UserBook >> genre: anObject [

	genre := anObject
]

{ #category : 'accessing' }
UserBook >> id [

	^ id
]

{ #category : 'accessing' }
UserBook >> id: anObject [

	id := anObject
]

{ #category : 'accessing' }
UserBook >> impression [

	^ impression
]

{ #category : 'accessing' }
UserBook >> impression: anObject [

	impression := anObject
]

{ #category : 'accessing' }
UserBook >> rating [

	^ rating
]

{ #category : 'accessing' }
UserBook >> rating: anObject [

	rating := anObject
]

{ #category : 'accessing' }
UserBook >> title [

	^ title
]

{ #category : 'accessing' }
UserBook >> title: anObject [

	title := anObject
]

{ #category : 'accessing' }
UserBook >> username [

	^ username
]

{ #category : 'accessing' }
UserBook >> username: anObject [

	username := anObject
]

{ #category : 'accessing' }
UserBook >> year [

	^ year
]

{ #category : 'accessing' }
UserBook >> year: anObject [

	year := anObject
]
